### ISSUE TITLE
Merged pull but collection not updated

### ISSUE THREAD

**Issue by skyrover7** [ordinals-wallet/ordinals-collections#102]
I can see that #87 was successfully merged and closed, but i dont see any updates to the collection itself

https://ordinalswallet.com/collection/ordinal-nouns

Note that someone had already added this collection with the wrong info, so I have updated it.

**Comment by skyrover7** [comment]
@MillHaus33 any thoughts here?

**Comment by MillHaus33** [comment]
had to write the update script, live now
