### ISSUE TITLE
Any other method to get json files to OrdinalsWallet?

### ISSUE THREAD

**Issue by smokinsarina** [ordinals-wallet/ordinals-collections#103]
I tried to do a pull request to add files for smokin sarina, but I don't understand if they were accepted or rejected. It said the files were merged, but they don't appear in the collections list.

I uploaded files to the branch for a second collection now.

**Comment by MillHaus33** [comment]
i havent merged any smoking sarin. create a fresh fork and try again. follow the pattern. once your pr is good ill merge.
