### ISSUE TITLE
Problems with pull request

### ISSUE THREAD

**Issue by AmazonWarriorsWorld** [ordinals-wallet/ordinals-collections#1045]
Hi! @MillHaus33 , About 20 hours ago you answered my problem, I had a problem with my pull requester always getting rejected. So, you told me to make a shorter slug, I did, but still my pull request was rejected, help me please, I would be very grateful!!!!
number of my pull request is 1044

**Comment by chrisconfirm** [comment]
Hello @AmazonWarriorsWorld, we are trying to get this sorted out. Please see my comment in #1044 . Thank you!

**Comment by chrisconfirm** [comment]
close issue. reason: pr #1044 was merged.
