### ISSUE TITLE
Issue with Pull request

### ISSUE THREAD

**Issue by btcpixelarmy** [ordinals-wallet/ordinals-collections#1046]
I am receiving this error "FAILED tests/test_colllections.py::test_home_structure - AssertionError: Top level changes are not allowed assert False"

**Comment by btcpixelarmy** [comment]
Pull request #1025

**Comment by crypticmeta** [comment]
you have made unnecessary files

**Comment by btcpixelarmy** [comment]
> you have made unnecessary files

I just tried to copy json files in collection folder as well when the error didnt disappear. How can i remove these files? and will it resolve my issue? Or shall i close and create new pull request?

**Comment by btcpixelarmy** [comment]
Again created new request #1064 and same error. I am creating inscriptions.json and meta.json on root. Dont know what is wrong

**Comment by crypticmeta** [comment]
Don't create in root.

Make a folder in collection folder. Make the files there. Only 2 files should be added. That's all.

**Comment by btcpixelarmy** [comment]
> Don't create in root.
> 
> Make a folder in collection folder. Make the files there. Only 2 files should be added. That's all.

Thanks dear this was the issue. I was creating files on root and the error was also showing something like the root issue.

How much time it takes for collection addition? How to follow up?

**Comment by crypticmeta** [comment]
No clue about when they will merge the request. Checkout ordscan.xyz. it's my project. 🫡

**Comment by btcpixelarmy** [comment]
> ordscan.xyz

Nice work and thanks for your support :) Surely will visit your web regularly,
