### ISSUE TITLE
Issue Pull Request

### ISSUE THREAD

**Issue by fsstudio234** [ordinals-wallet/ordinals-collections#1057]
Please Acc my Pull Request #1056

**Comment by fsstudio234** [comment]
Please Acc my Pull Request https://github.com/ordinals-wallet/ordinals-collections/pull/1056

**Comment by minidogenft** [comment]
this request should not have been accepted, you are using other people inscriptions ids:
in your meta.json you use the same inscription_icon as matrix ordinals : 2fbad0d06111466e05e4732e73cd23568d22da509445e6842e18922e1afe205fi0

and in your inscriptions.json you also use a matrix ordinals inscription id : 
c4e75a74e25a9295095061f41ad724bbdaed092499d6092b3500fbb1eed6cb5di0

what are you trying to achieve ?
