### ISSUE TITLE
smokin sarina

### ISSUE THREAD

**Issue by smokinsarina** [ordinals-wallet/ordinals-collections#111]
i'm trying - is there no consideration for artists? - i've never used githud before. - bitister was nice enough to provide json files from my listing at ordynals.com --

i'd really like to get these listed, but i just don't understand how to do this. 

i just have 2 small collections that I'm trying to list. a 12 piece & a 29 piece

**Comment by SecondSarinaAccount** [comment]
Created a second sarina account because i couldn't figure out how to delete any files or forks from the first one. - But it looks like the pr failed again. -- this is my 4th day of trying to submit these collections.

Is there some point where you offer to assist? -- please!

**Comment by SecondSarinaAccount** [comment]
bitister had said that maybe you require a .png instead of .jpg file for the icon pic.

Is that maybe the problem? --if so, I can open a 3rd GitHub account and try again with .png icons.
