### ISSUE TITLE
updating inscriptions.json fail

### ISSUE THREAD

**Issue by starbackr** [ordinals-wallet/ordinals-collections#1119]
how can I update the inscriptions.json?

I want to add inscriptions, but the pull request fails: 

`#!/bin/bash -eo pipefail
python -m pytest
============================= test session starts ==============================
platform linux -- Python 3.8.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/circleci/project
collected 5 items                                                              

tests/test_colllections.py ....F                                         [100%]

=================================== FAILURES ===================================
_______________________________ test_uniqueness ________________________________

    def test_uniqueness():
        input_collections = os.listdir(COLLECTIONS)
        print('\n\n')
    
        # add new collections
        all_inscription_ids = []
        for collection in input_collections:
          with open("{}/{}/inscriptions.json".format(COLLECTIONS, collection), "r") as file:
            inscriptions = json.load(file)
          inscription_ids = []
          for x in inscriptions:
            inscription_ids.append(x.get('id'))
          all_inscription_ids = all_inscription_ids + inscription_ids
          duplicates = len(all_inscription_ids) - len(set(all_inscription_ids))
>         assert duplicates == 0
E         assert 1 == 0

tests/test_colllections.py:91: AssertionError
----------------------------- Captured stdout call -----------------------------

=========================== short test summary info ============================
FAILED tests/test_colllections.py::test_uniqueness - assert 1 == 0
========================= 1 failed, 4 passed in 2.42s ==========================

Exited with code exit status 1
CircleCI received exit code 1`

**Comment by minidogenft** [comment]
thats because of #1056 he is using someone else inscription id and now no one can pass circleci tests

**Comment by starbackr** [comment]
gosh...

**Comment by ferre138** [comment]
Is this still there?

**Comment by starbackr** [comment]
I even tried to make a new fork. the same problem with failed ci/circleci validation persists. 
What can we do to fix this?

**Comment by starbackr** [comment]
can anybody tell me please what causes this problem?

**Comment by starbackr** [comment]
unsolved
