### ISSUE TITLE
Display Blitkin collection as <object> instead of <img> to correctly display

### ISSUE THREAD

**Issue by sayangel** [ordinals-wallet/ordinals-collections#1133]
Our SVGs have embedded code to make them dynamic. This allows us to do interesting things like modify them on the fly. Unfortunately, this means they can't be rendered via `<img>`. I am requesting they be displayed as objects and have confirmed this works. See below for requested changes.

This is what an item in our collection currently displays as:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3604426/224835944-c7a80479-1c61-45ea-9656-c77e30375383.png">

The code currently used to display the image is 
```
<img class="page_content__HT_T4 InscriptionContent_image__QTQgG" src="https://turbo.ordinalswallet.com/inscription/content/b82fd9c1118c753a14616635804ff53743ee9512c9fd74817f19522cce164a45i0">
```

If modified to be 
```
<object type="image/svg+xml" class="page_content__HT_T4 InscriptionContent_image__QTQgG" data="https://turbo.ordinalswallet.com/inscription/content/b82fd9c1118c753a14616635804ff53743ee9512c9fd74817f19522cce164a45i0" t=""></object>
```

then the item displays as intended

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/3604426/224836394-71ed7b55-b3f8-4c6c-bd5b-73e5bc9747a9.png">

**Comment by MillHaus33** [comment]
smart. stay tuned.
