### ISSUE TITLE
Bitcoin Ghosts

### ISSUE THREAD

**Issue by ggalin** [ordinals-wallet/ordinals-collections#122]
Hi - I would like to add my collection,  but I need a little hand holding to upload the 2 json files correctly.
I think the format is good,  but I got errors because no directory I was trying to put it in....
Please let me know how to proceed

thank you

**Comment by ggalin** [comment]
HI - I appreciate the help,  just let me know what I need to do

**Comment by MillHaus33** [comment]
do your best to follow readme, and look at how other collections did it
