### ISSUE TITLE
cannot update the already existing inscriptions.json

### ISSUE THREAD

**Issue by starbackr** [ordinals-wallet/ordinals-collections#1258]
I added 

- 13 inscriptions to the inscriptions.json 
- trait "Clothing" to all inscriptions

Pull Request doesn't go through
Even tried a fresh new fork, but still it fails the circlecl with this error.

Anyone have a clue?

`#!/bin/bash -eo pipefail
python -m pytest
============================= test session starts ==============================
platform linux -- Python 3.8.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/circleci/project
collected 5 items                                                              

tests/test_colllections.py ....F                                         [100%]

=================================== FAILURES ===================================
_______________________________ test_uniqueness ________________________________

    def test_uniqueness():
        input_collections = os.listdir(COLLECTIONS)
        print('\n\n')
    
        # add new collections
        all_inscription_ids = []
        for collection in input_collections:
          with open("{}/{}/inscriptions.json".format(COLLECTIONS, collection), "r") as file:
            inscriptions = json.load(file)
          inscription_ids = []
          for x in inscriptions:
            inscription_ids.append(x.get('id'))
          all_inscription_ids = all_inscription_ids + inscription_ids
          duplicates = len(all_inscription_ids) - len(set(all_inscription_ids))
>         assert duplicates == 0
E         assert 1 == 0

tests/test_colllections.py:91: AssertionError
----------------------------- Captured stdout call -----------------------------

=========================== short test summary info ============================
FAILED tests/test_colllections.py::test_uniqueness - assert 1 == 0
========================= 1 failed, 4 passed in 4.15s ==========================

Exited with code exit status 1
CircleCI received exit code 1`

**Comment by starbackr** [comment]
alright, I tried deleting the directory now. That seems to work for now...

**Comment by pifunft** [comment]
I have the same error. Did you manage to pass that? Could you please explain? thanks

**Comment by starbackr** [comment]
not yet. as there is no solution provided by the team, i now requested to delete our directory. this went through. As soon as it is deleted I will submit a fresh directory.

**Comment by starbackr** [comment]
I am looking for a fix for more than a week. 
do you even care?

**Comment by starbackr** [comment]
HELLOOOOOO???? 

SUPER disappointing. We are losing sales every day. YOU are losing sales every day.

**Comment by bimal1665** [comment]
you have problem on your inscriptions.json file bro

**Comment by starbackr** [comment]
> you have problem on your inscriptions.json file bro

no that is not the case
