### ISSUE TITLE
When can we get listed? - 123

### ISSUE THREAD

**Issue by 123dobby** [ordinals-wallet/ordinals-collections#1345]
Pulled request 3 weeks ago. I was told my collection will be added. I've contacted you here many times, also on Twitter no response. Could you pls let us know if there's anything else to do from our side? 

https://twitter.com/123ordinals

@MillHaus33

**Comment by MillHaus33** [comment]
https://ordinalswallet.com/collection/123 is this you?

**Comment by chrisconfirm** [comment]
Hello @123dobby , we would like to check back if the issue was resolved. Are you happy with the metadata in /collections/123 or is there anything we can update for you there? Thank you for your patience.

**Comment by chrisconfirm** [comment]
close issue. reason: collection is in /123
