### ISSUE TITLE
Socials links missing on our collection.

### ISSUE THREAD

**Issue by 007EagleEye** [ordinals-wallet/ordinals-collections#1490]
Please add our socials to our collection "OrdinalKongz". 

The collection was submitted by CoinYeezy in February, we haven't heard from him since. 

Twitter: https://twitter.com/OrdinalKongz
Discord: https://discord.gg/ordinalkongz
![Screenshot_25](https://user-images.githubusercontent.com/108618837/226901304-8e84b282-6f3c-4741-b52c-2a5ff4e94f05.jpg)

Thank you!

**Comment by MillHaus33** [comment]
https://ordinalswallet.com/collection/ordinal-kongz
