### ISSUE TITLE
Updated inscriptions.json file but still remain the old version in the website

### ISSUE THREAD

**Issue by OrdinalAllStars** [ordinals-wallet/ordinals-collections#1509]
I opened a pull request to change the inscriptions.json file (for Ordinal All-Stars) and it got accepted and merged by @MillHaus33, but our collection isn’t changed since then, like if he didn’t ever merged the new file and still remain the old version. 
Is there a problem or do we have only to wait more? It’s already been 19 hours

**Comment by nezta-pointsute1** [comment]
My collection has the same problem. #1247
It has been merged, but the ordinalswallet display is still the same.
Please reflect yesterday's merge to the ordinalswallet site.

**Comment by MillHaus33** [comment]
https://github.com/ordinals-wallet/ordinals-collections/pull/842

is this the pr 

@OrdinalAllStars

**Comment by chrisconfirm** [comment]
Hello @OrdinalAllStars, can we close this issue? Thank you for your feedback.

**Comment by chrisconfirm** [comment]
closing issue. reason: issue seems fixed.
