### ISSUE TITLE
Collection not updating on ordinalswallet.com after pull request merge

### ISSUE THREAD

**Issue by challengepunks** [ordinals-wallet/ordinals-collections#1521]
Hello Ordinals Wallet team,

I'm writing to inform you about an issue I'm facing with my collection "Challenge Punks". I recently submitted a pull request to update the inscriptions.json and meta.json files (PR link: https://github.com/ordinals-wallet/ordinals-collections/pull/1399), and it was merged successfully by @MillHaus33. The updated version of the collection has been reflected on openordex.org after the pull request merge, but it hasn't been updated on ordinalswallet.com.

Could you please take a look at the situation and let me know what the next steps are to resolve the issue? I appreciate your help in getting this sorted out.

Thank you,
Challenge Punks

**Comment by OrdinalAllStars** [comment]
We are many with this problem. @MillHaus33 and the team please fix this

**Comment by MillHaus33** [comment]
these should all be synced up now. open a new issue and link the pr you want synced if not.
