### ISSUE TITLE
hello Ordinals Wallet Team Please merge the PRs.

### ISSUE THREAD

**Issue by acca3434** [ordinals-wallet/ordinals-collections#1639]
hello Ordinals Wallet Team

Please merge the PRs. The number is #1638.

Thank you as always.

**Comment by minidogenft** [comment]
please add #1837 too thank you :)

**Comment by minidogenft** [comment]
please merge  #1843 too, thank you :)

**Comment by chrisconfirm** [comment]
Closing this Issue. Reason: pr #1639 was merged on April 1st. Thank you @acca3434
