### ISSUE TITLE
It's been two days, I would appreciate it if you could tell me what I need to do Wallet team.

### ISSUE THREAD

**Issue by acca3434** [ordinals-wallet/ordinals-collections#1670]
My number is #1638.

Please merge.

**Comment by cliobitcoinbank** [comment]
It's not a team its just some guy.

**Comment by StellarStoic** [comment]
Same issue #1938 . They merge higher numbers of my pull request and looks like some of us have been skipped or we don't understand their workflow. They have some automatic process in place which I don't think works and it does not merge our pull requests into the main branch or someone like @MillHaus33 should just push the button. that should not be so hard.

**Comment by chrisconfirm** [comment]
was merged April 1. Closing this issue.
