### ISSUE TITLE
I can't update my correction, onokun

### ISSUE THREAD

**Issue by ALiberalVoluntarist** [ordinals-wallet/ordinals-collections#1710]
I created it 3weeks ago. Then later we found a mistake on our inscription.json. So we updated it and did pull request one week ago, but still it is not in the main collection page. Please help us to update.
 https://github.com/ordinals-wallet/ordinals-collections/pull/1571

**Comment by chrisconfirm** [comment]
Closing this issue. Reason: merged on April 1st. Thank you @ALiberalVoluntarist
