### ISSUE TITLE
Ascii collection not displaying correctly

### ISSUE THREAD

**Issue by bitcoinranas** [ordinals-wallet/ordinals-collections#1797]
Please check icon and inscriptions range not showing:
https://ordinalswallet.com/collection/ranas
Also trying to Search my collection using word "ranas" but not found.

Thanks

**Comment by chrisconfirm** [comment]
@bitcoinranas do you still have this issue? please comment or close. thank you.

**Comment by chrisconfirm** [comment]
closing issue. reason: can be found in search as "ranas", icon is showing and inscriptions range as well.
