### ISSUE TITLE
https://ordinalswallet.com/collection/bitcoin-apes

### ISSUE THREAD

**Issue by lolil9874** [ordinals-wallet/ordinals-collections#182]
hey it still doesnt work :/

**Comment by lolil9874** [comment]
https://github.com/ordinals-wallet/ordinals-collections/tree/main/collections/bitcoin-apes

**Comment by spzjulien** [comment]
what's the problem ?

**Comment by lolil9874** [comment]
> what's the problem ?
> 
> 

We can't access to https://ordinalswallet.com/collection/bitcoin-apes and the collection doesn't shows up :/
