### ISSUE TITLE
Update ABL (A Beautiful life) .json file 

### ISSUE THREAD

**Issue by BitcoinBugsy** [ordinals-wallet/ordinals-collections#1958]
Added 4 additional inscriptions to the collection

[
	{
		"id": "445de39f8db7c65515c9972d5d668d3f91fee153e34eca96541ce4562851ff3ai0"
	},
	{
		"id": "0756a2849921688e6846674fddab50c3b5835de61e5f3646227fdd77b3bdd4bfi0"
	},
	{
		"id": "77cd48fbe950046812623f462688814c7bf9b16e0cd901797d99b3f2015f59d5i0"
	},
	{
		"id": "72130940272ca630d89bfd5a777a71985e02e2ece35d450e2d03f90fafb0a492i0"
	},
	{
		"id": "8ca48141478c26ff8ec1f3e35d08f440b60e107981a21fd5138c9c78c1f7d48ci0"
	},
	{
		"id": "a6183d33a3fcc74c89f0afaf069aa06904c67af01d800a2e7235505cae68ca9ai0"
	},
	{
		"id": "dcbd3b564d44072e788133e2383a34867f159783a33076e184c7f71cef6efffai0"
	}
	{
		"id": "a21d6b88be3a28c6c2e7cea0e732a906f6f172328de81919c9750a8083170531i0"
	}
]

**Comment by chrisconfirm** [comment]
Closing issue. Reason: Updated with pr #2289 and #2290
