### ISSUE TITLE
The collection is not displaying the correct meta name and total supply

### ISSUE THREAD

**Issue by nakamotocryptocard** [ordinals-wallet/ordinals-collections#1965]
Hi @MillHaus33 
Thank you for listing the Nakamoto Crypto Cards collection without requiring a merge PR.

https://ordinalswallet.com/collection/nakamoto-crypto-cards

However, the meta name and total supply information are currently not displaying accurately. We need the correct information to be displayed as per the following PR: https://github.com/ordinals-wallet/ordinals-collections/pull/1944

**Comment by chrisconfirm** [comment]
#1944 was merged on April 24. Closing this issue. Thank you!
