### ISSUE TITLE
A note to the mods

### ISSUE THREAD

**Issue by StellarStoic** [ordinals-wallet/ordinals-collections#2004]
Ok, guys and gals and mods and modesest, hear me out. Please onboard more contributors that will have the right to merge with the main branch. The last merge was 3 days ago and some users are complaining that their pull has not been merged for two weeks.  I also noticed that the practice was skipping pull requests. This is purely biased and unacceptable. Maybe you should change the REDME.md file header from... 

~~Ordinals Collections Standards~~ 

to

# Our Collections Standards #

**Comment by minidogenft** [comment]
i kind of thought this was a global repo too that would help to promote all ordinals. I am sad to see i can't even update my collection anymore. I know its a lot of work but yet...  We can see updates for promoted collections. If this is not supposed to be a global repo to help ordinals grow, let us know ordinals wallet. Thank you

**Comment by chrisconfirm** [comment]
Hello @StellarStoic , thank you for your feedback. Please bear with us while we are working on everything. I personally do have much love for smaller collections as well. Thank you for your understanding. And let me know if you have a current issue open for one your collections.
