### ISSUE TITLE
Please approve Update #2017

### ISSUE THREAD

**Issue by Bitamigos** [ordinals-wallet/ordinals-collections#2019]
We are trying to add the real Bitamigos collection. Our community has been inscribing since early 600k and we are already listed on other marketplaces. We are also the only REAL Bitamigos collection with no duplicates or copy and paste to any Ethereum based collection.

**Comment by chrisconfirm** [comment]
"...with no duplicates or copy and paste to any Ethereum based collection." it sure looks similar to nakamigos 
close pr. reason: merged pr #2016
