### ISSUE TITLE
ordinal humans pfp

### ISSUE THREAD

**Issue by ordinalhumans** [ordinals-wallet/ordinals-collections#2107]
Hey there, uploaded 6e27a1f92f42d1e41a45a949cb4ed475ced7fd93d012a011f451c30e8d0fe3adi0 as a pfp in meta.json, but it uploaded a random ordinal, could you please change it?

**Comment by chrisconfirm** [comment]
Hello @ordinalhumans , we changed your inscription_icon to 6e27a1f92f42d1e41a45a949cb4ed475ced7fd93d012a011f451c30e8d0fe3adi0. Thank you for your patience. Closing this issue now.
