### ISSUE TITLE
Pull request( April 4th)

### ISSUE THREAD

**Issue by xxy1996** [ordinals-wallet/ordinals-collections#2153]
we have updated and submitted our new collection on April 4th but it still hasn't been merged, could you help us to check the reason?
![image](https://user-images.githubusercontent.com/115043112/233822761-287d9854-44c7-4995-ba61-0960e02cd012.png)

**Comment by bigcrypSv** [comment]
This merge issue is same day I attached Twetch and Ordinals wallet. Which is when my entire Ord wallet was emptied/stolen,any connection?

**Comment by chrisconfirm** [comment]
#1806 was merged May 2- closing this issue.

**Comment by bigcrypSv** [comment]
It's hasn't been addressed at all and nothing to explain how my ordinals wallet emptied while Twetch was protected from theft.

**Comment by chrisconfirm** [comment]
please open a separate issue for this with more details. this issue here was by @xxy1996 on BTCDOMAIN collection
