### ISSUE TITLE
April 7th  PR #1843 still not merged ?

### ISSUE THREAD

**Issue by minidogenft** [ordinals-wallet/ordinals-collections#2225]
Can you please let me know why you don't merge https://github.com/ordinals-wallet/ordinals-collections/pull/1843 ?
I have been asking several times now and even raised a ticket in your discord back then. I was told there should be no problem.

Please help.

**Comment by minidogenft** [comment]
Can you please let me know why you don't merge #1843 ? 
I have been asking several times now and even raised a ticket in your discord back then. I was told there should be no problem. 

Please help.

**Comment by chrisconfirm** [comment]
sorry @minidogenft , please comment in #1843 on your relation to pimax1, who it seems updated meta on this collection before you? thank you for your patience.

**Comment by minidogenft** [comment]
sure thank you

**Comment by chrisconfirm** [comment]
closing issue. Reason: #1843 merged
