### ISSUE TITLE
Add collection

### ISSUE THREAD

**Issue by apepix** [ordinals-wallet/ordinals-collections#2231]
where have i to send or upload the 2 .json documents ?

**Comment by cliobitcoinbank** [comment]
Here is a short guide on the Bitcoin Ordinals Wikia: 
https://bitcoinordinals.fandom.com/wiki/How_to_List_an_Ordinals_Collection

If you get stuck or need help ask on the r/BitcoinOrdinals subreddit here: 
https://www.reddit.com/r/BitcoinOrdinals/

The reddit also has a wiki of its own with guides and links:  
https://www.reddit.com/r/BitcoinOrdinals/wiki/index/resources/

**Comment by chrisconfirm** [comment]
@apepix , are the guides helping you? Do you have meta.json and inscriptions.json prepared already? 
Navigate to ordinals-wallet/collections. Then try to create a file there, which should then create your own fork of the repository. in your own fork you will put the 2 jsons under /collections/your-collection-name . The "slug" within the meta.json should ideally be your-collection-name as well. Please try and you can let me know the pull request number here.

**Comment by apepix** [comment]
sorry , posible its my inability to code .
I have the meta.json and inscriptions.json.

when i go to ordinals-wallet/collections, and click the button , it redirects me to github (that i dont know how to manage it)

**Comment by apepix** [comment]
i think i do it .
can you help me to be sure ?
https://github.com/apepix/Bitcoin-TradeMarks-8k-47k-

**Comment by chrisconfirm** [comment]
not correct yet. meta.json and inscriptions.json need to be in /collections/your-collection-name/ !!! and if you have them there, then you can create a pull request we can work with

**Comment by apepix** [comment]
thanks so much 

https://github.com/apepix/Bitcoin-TradeMarks-8k-47k-/tree/main/collections

i think its in there, can you check it ?

**Comment by apepix** [comment]
https://github.com/apepix/Bitcoin-TradeMarks-8k-47k-/tree/main/collections/Bitcoin%20TradeMarks%20(8k-47k)

**Comment by chrisconfirm** [comment]
create a pull request

**Comment by apepix** [comment]
thx
-Add files via upload #2322-

https://github.com/ordinals-wallet/ordinals-collections/pull/2322

**Comment by chrisconfirm** [comment]
issue closed. pull request not merged. reason: pictures of trademarks. thank you for your understanding.

**Comment by chrisconfirm** [comment]
what kind of logos? i don't know. did you inscribe them?

**Comment by apepix** [comment]
yes , this is one of them

https://ordinals.com/inscription/4d6beb959faccf7923f0be6e1170c0f9327e36cc8c0037a3bb80e764ebddaaf1i0

**Comment by chrisconfirm** [comment]
please open a pull request if you want to list a collection that you inscribed.
