### ISSUE TITLE
Looks like there's no other way

### ISSUE THREAD

**Issue by StellarStoic** [ordinals-wallet/ordinals-collections#2236]
I wouldn't open an issue if my pull request for my small collection would've been approved in less then a month and becouse I see there's no particular order and pull requests are skipped, Im complaining why this small and simple project hadn't been merged yet? It really wouldn't take someone more then just a click 🙁

https://github.com/ordinals-wallet/ordinals-collections/pull/1981

**Comment by cliobitcoinbank** [comment]
Sorry if this is basic, Did you put them both into the correct folder with the name the same as your slug? If your files were valid they should be merged by now.

**Comment by StellarStoic** [comment]
> Sorry if this is basic, Did you put them both into the correct folder with the name the same as your slug? If your files were valid they should be merged by now.

Yes the folder name is the same as the slug. I don't think circleci would pass the test if they were different.

**Comment by cliobitcoinbank** [comment]
Okay, so was it "TutiFruti Women" or something like that?  Seeing an account Golem01, is that you or someone else?

**Comment by cliobitcoinbank** [comment]
If it was tutifruti women, I notice that the files are in the root directory, and not the correct folders: 
[collections/inscriptions.json] [collections/meta.json] 
These two should be changed to 
[collections/SLUGNAME/inscriptions.json] [collections/SLUGNAME/meta.json]
Maybe you are being rejected because your stuff is incorrect, not because maintainers are lazy or biased?

**Comment by StellarStoic** [comment]
Look at my issue post @cliobitcoinbank ... It's all there, even the link to my collection pull requests which was fone as the specs said it should be done.

What tuti-fruti are you talking about?
Golem? What golem? Can't you see what my username is? We're on GitHub, what is stopping you from doin 2-3 extra clicks 😆

**Comment by StellarStoic** [comment]
Thank you but as I said before. Everything is in my pull request https://github.com/ordinals-wallet/ordinals-collections/pull/1981. I don't know what else do you need 🤷

**Comment by cliobitcoinbank** [comment]
Whatever, just trying to verify the name and a few other details with you first but I can just copy paste what you already have, just because you passed the tests doesn't mean stuff is correct and that might prevent your collection from getting listed.

**Comment by StellarStoic** [comment]
It got merged into main 🙏 Thank you @cliobitcoinbank for helping and thank you @chrisconfirm to merge it into main 🫂

**Comment by cliobitcoinbank** [comment]
Went and checked out your collection now that it is listed, really cool how it generates more combinations that atoms in the universe and all the other deep math stuff that went into them.  Definitely much more going on than what you see on the surface with these. 
Please please come advertise your collection on the r/BitcoinOrdinals subreddit and just ask ClioBitcoinBank or DaveBra if automod gives you any crap or you need a post approved etc.  Great work!

**Comment by chrisconfirm** [comment]
Hello @StellarStoic , thank you for your patience. Can this issue be closed?
