### ISSUE TITLE
Please tell me is there a way to show all collections listed under this page instead of only 1000?

### ISSUE THREAD

**Issue by Demon-devil** [ordinals-wallet/ordinals-collections#2276]
https://github.com/ordinals-wallet/ordinals-collections/tree/main/collections

**Comment by Demon-devil** [comment]
I just want to know how to get all the collection data of more than 1000 pieces，thanks～

**Comment by chrisconfirm** [comment]
you create a fork in github, or go to /ordinals-collections and download the .zip 
does this answer your question?

**Comment by Demon-devil** [comment]
> 
Is there a better way such as page fetching instead of getting the full amount without downloading?

**Comment by chrisconfirm** [comment]
this is a github-specific, not particularly related to this repo. i do not have another solution at hand other than what stated above. please do your own research on this github-specific issue. Thank you for your understanding.
