### ISSUE TITLE
Support for Artists

### ISSUE THREAD

**Issue by lyndoncore** [ordinals-wallet/ordinals-collections#228]
Would love to see support for "date", and "description" fields added (outside of arbitrary attributes).

As a photographer, would also be happy to see a "location" field added. 

This might help create a more inclusive environment for non-generative artists to contribute to the ordinals ecosystem. 

- with love

**Comment by MillHaus33** [comment]
get creative on how you use the attributes

``` "attributes": [
        {
          "trait_type": "Location",
          "value": "Canada"
        },
        {
          "trait_type": "Date",
          "value": "2023-02-27",
                  },
        {
          "trait_type": "Description",
          "value": "My photo",
                  }
      ]```
