### ISSUE TITLE
/bitcoin-sneakers #68 not showing in collection page

### ISSUE THREAD

**Issue by chrisconfirm** [ordinals-wallet/ordinals-collections#2298]
@MillHaus33 see last comment in pr #2291

-> Sneaker #68 https://ordinalswallet.com/inscription/db67d2c57c23b42b6fb5f695041b1272c5a9d79f3ab47c647a2c3e5b834bfbe9i0
-> is part of /bitcoin-sneakers/inscriptions.json 
-> but not showing on the collection page https://ordinalswallet.com/collection/bitcoin-sneakers 

Can we figure out why?

**Comment by bitcoinsneakers** [comment]
Not sure if this helps at all but I know originally it was a duplicate ID .. maybe something happened there

**Comment by chrisconfirm** [comment]
close pr. reason: 68 is now showing on the collection page
