### ISSUE TITLE
How to modify or remove a collection?

### ISSUE THREAD

**Issue by btek0909** [ordinals-wallet/ordinals-collections#2318]
Thank you!

**Comment by btek0909** [comment]
Please remove btc5-5 (btc5x5) collection for now thank you!

**Comment by chrisconfirm** [comment]
can you link the original pull request that was for listing the collection? i can't find it and it's the easiest way to check if you are associated to it. Thank you for your understanding.

**Comment by chrisconfirm** [comment]
removing collections/btc5-5 with pr #2373 . hope you have made a backup yourself, in case you want to have it added again, you will have to open a new pull request with the jsons.
