### ISSUE TITLE
Guys, thanks for the fast merge, but what is the use if you dont sync the website?

### ISSUE THREAD

**Issue by starbreeders-singularity-dao** [ordinals-wallet/ordinals-collections#2323]
... just asking for a friend

**Comment by minidogenft** [comment]
Hi hi, same issue here, both my collections PR were updated with  #1843 but the website still has old infos of our main collection and second collection is not listed.

**Comment by cliobitcoinbank** [comment]
Gotta say unfortunately Blockchain Fossils is also suffering this issue. I am considering small changes just to get another commit to see if it "takes".  Let us know if we should post somewhere else for this issue?

**Comment by starbreeders-singularity-dao** [comment]
hello, any ideas, anyone??

**Comment by starbreeders-singularity-dao** [comment]
hello, any solution in sight?

**Comment by cliobitcoinbank** [comment]
The blockchain fossils collection hasnt updated either. I dont think we are complaining in exactly the right place for site related issues but if the collections guys figure out the problem I think they would tell us.  I have subscribed to this thread and I'm trying to keep them updated but not bug them too much because it might not be in control of the website.

**Comment by minidogenft** [comment]
please do something guys. I need my collection to be updated, its been more than a month.

**Comment by minidogenft** [comment]
@chrisconfirm any idea whats going on?

**Comment by starbreeders-singularity-dao** [comment]
Hello, waiting for 2 weeks now.... not a drama for as, as were selling everything on magic eden instead, but ... hmmm

**Comment by minidogenft** [comment]
guys when will the website sync with the repo ? Please let our holders trade Pixel doges on ordinalswallet

**Comment by starbreeders-singularity-dao** [comment]
pure ignorance. pretty interesting.

**Comment by starbreeders-singularity-dao** [comment]
guys, why is your marketplace not updating for more than a month? you cant be serious just ignoring this.

**Comment by starbreeders-singularity-dao** [comment]
hello, would you please set up a solution to apply for an update on ordinalswallet.com? Our collection got updated here, but is not updated on the marketplace for more than a month. This is really a bad thing as we can not sell our added ordinals.

**Comment by starbreeders-singularity-dao** [comment]
guys, the marketplace is STILL using the outdated json file. wrong traits, and many inscriptions not listed. WHYYYYY

**Comment by minidogenft** [comment]
have you managed to get help ? I never got any explanation. 

in this repo, no answer. 
In discord they used to say it should work and said I should wait and closed the ticket. Now we cant open ticket in discord anymore.

Now i am trying their support through.
They forwarded me to the repo dev but no answer anymore. 

I never got any explanation what is wrong, why is the website ourdated vs the repo for more than 2 months now ?

why you dont the dev does not answer at all ?

**Comment by starbreeders-singularity-dao** [comment]
no, its a bad joke really. but after all, people will trade our nfts somwehere else. it is more their problem than ours. I dont really care anymore. It is just unprofessional.

**Comment by starbreeders-singularity-dao** [comment]
@MillHaus33 what is the issue? is it because we updated our account name? please update your marketplace.

**Comment by cliobitcoinbank** [comment]
> @MillHaus33 @chrisconfirm what is the issue? is it because we updated our account name? Our repo is still the same. Please update your marketplace.

To confirm, Is your collection showing properly on sites like ord.io or openordex.org??  Ordinals wallet is clearly having some major internal problems preventing updates at this time so it may be best to check other sites to see if your collection is showing properly.

**Comment by starbreeders-singularity-dao** [comment]
> ord.io

hi, yes the collection is displayed correctly on other sites! We have 364 ordinals in the json, but on ordinalswallet only displays 131, like it was before the last update. and that was more than 2 months ago.

**Comment by starbreeders-singularity-dao** [comment]
hello, this problem is still unsolved!!! 4 months now.
