### ISSUE TITLE
preparing to add collection 

### ISSUE THREAD

**Issue by apepix** [ordinals-wallet/ordinals-collections#2334]
i want to create a collection of 170 bitcoin logos .
is it allowed ? i want to know it before prepare the .json archive

**Comment by Gaviar** [comment]
Hello, I'm also interested in how to download the collection, have you figured something out yet??

**Comment by cliobitcoinbank** [comment]
They have rejected people on the grounds of copyright before so one way to check is just to submit commit and hope it all works out.

**Comment by chrisconfirm** [comment]
@apepix if it is your collection it should be fairly simple to make a .json for you. if you are not the creator of the collection then please clearly state the reason why you are submitting metadata to inscriptions.
What you can always so is you can inscribe your own original collection and then open a pull request with the metadata.

**Comment by chrisconfirm** [comment]
closing pr.
