### ISSUE TITLE
Add VV Checks

### ISSUE THREAD

**Issue by tallrooster** [ordinals-wallet/ordinals-collections#2354]
This wallet is Jack Butcher, the creator of VV Checks and Opepen. Can we add this collection?

bc1p8syvw72h69sw00cp083vu5kdpa6k54z3fapmn654vqsda7j5qpysrsh0ue

Proof: https://t.co/CN6OcDs9UV

**Comment by shahin7071** [comment]
Hi

**Comment by tallrooster** [comment]
Hi there.

**Comment by chrisconfirm** [comment]
please open a pull request with the metadata jsons in /ordinals-collections/collections/name-of-your-collection/meta.json and inscriptions.json . thank you

**Comment by chrisconfirm** [comment]
close issue. reason: @tallrooster needs to open a pull request, see comment above
