### ISSUE TITLE
Inscription not showing up in collection

### ISSUE THREAD

**Issue by Trabbtc** [ordinals-wallet/ordinals-collections#2400]
Hi,
Not sure how this works.
I have an inscription (ff1bfe70d4a558c1da96c5fd512e84fa46b782ab9dbd8aaf5c58f0014036b543i0) that belongs to the collection btcdomain, but when I listed it for sale it doesnt come up as if it were part of the collection.
How do I go about it?
Thanks

**Comment by Tsumer97** [comment]
Это может быть связано с тем, что для продажи символов из коллекции btcdomain необходимо иметь права на управление символами, как владелец или администратор. Если вы не являетесь владельцем или администратором символа, то вы не можете продать его в рамках коллекции btcdomain.

Также необходимо убедиться, что символная монета (токен) соответствующая вашему символу, была добавлена в ваш кошелек, и вы имеете на нее права.

Если вы имеете права на символ и его соответствующую токен монету, и продажа по-прежнему не происходит, то это может быть связано с технической проблемой или ошибкой в процессе продажи.
