### ISSUE TITLE
Delicious punks "slug" not registered correctly

### ISSUE THREAD

**Issue by chrisconfirm** [ordinals-wallet/ordinals-collections#2471]
@MillHaus33 
the "slug" in delicious punks meta.json is "delicious-punks", 
and the meta seems fine in https://github.com/ordinals-wallet/ordinals-collections/edit/main/collections/delicious-punks/

--> BUT the collection site on ordinalswallet links to "https://ordinalswallet.com/collection/delicious%20punks" and is not showing correctly?

Can you help fixing this? Thank you.

**Comment by DeliciousPunks** [comment]
I've done your request and re-pulled the request, please help me see if anything is wrong, thank you.
