### ISSUE TITLE
Merge #2488 + Issues pertaining to the copy paste Bitamigos

### ISSUE THREAD

**Issue by Bitamigos** [ordinals-wallet/ordinals-collections#2489]
Please merge #2488 so we can update our collection and allow our holders to trade. 

We will also be taking legal action against the copy and paste Nakamigos collection for infringing upon our brand IP as the names "Bitamigos" and "Real Bitamigos" are both registered trademarks that we own. We will be sending you guys cease and desist letters within the next few days and encourage you to take measures sooner by either delisting the copy paste Nakamigos collection or making them change their name to something like "Bitcoin Nakamigos". Legal suit may follow if demands are not met within reasonable time.

**Comment by chrisconfirm** [comment]
At the moment, I can not find a "bitamigo" IP in the TESS: https://tmsearch.uspto.gov/bin/showfield?f=toc&state=4802%3A4gi20p.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_tagrepl%7E%3A=PARA1%24LD&expr=PARA1+AND+PARA2&p_s_PARA2=bitamigos&p_tagrepl%7E%3A=PARA2%24COMB&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query 

Please advise how we can check your references and your relation to nakamigos. I have not found the necessary information yet. Please understand that it does not help opening 18 pull requests in a row, and please also note that I left your last pr remaining open and referenced your previous prs to it.

**Comment by Bitamigos** [comment]
We were having trouble passing circle so we had to open up new prs in order
to pass it. We kept having duplicate issues but since solved them. Can you
merge the prs? Also give us a couple of days and you will see it in USPTO.
