### ISSUE TITLE
Actually Just Had Some Noob Creator Questions

### ISSUE THREAD

**Issue by Master-Zomon** [ordinals-wallet/ordinals-collections#2549]
Can I start a creators project with the ultimate goal of having around 1000 pieces but only start with say 10 at a time and go as I please slowly growing the collection?

Can I batch inscribe the collection or do they need to be one at a time?

Each time I do add to the collection how do I make sure it gets added to the same collection on ordanals wallet as the latest addition?

Thanks for your help!

**Comment by cliobitcoinbank** [comment]
> Can I start a creators project with the ultimate goal of having around 1000 pieces but only start with say 10 at a time and go as I please slowly growing the collection?

Yes!

> Can I batch inscribe the collection or do they need to be one at a time?

Either will work

> Each time I do add to the collection how do I make sure it gets added to the same collection on ordinals wallet as the latest addition?

You will create your own folder on the ordinals-collections github page and whoever created the folder is usually the only person that can add to that specific collection.
