### ISSUE TITLE
What's the wait time for a collection to be listed?

### ISSUE THREAD

**Issue by heybol** [ordinals-wallet/ordinals-collections#2828]
Hi @MillHaus33 

Just checking to see whats the wait time for a collection to be listed. My collection name is "Nakabros" #2821 

Thanks

**Comment by cliobitcoinbank** [comment]
Give it a day before you start @ing maintainers.

**Comment by monooz23** [comment]
HI can anyone help me with this error I keep getting @cliobitcoinbank ?
loning into 'C:\Users\User\Documents\Github\ordinals-collections'...
remote: Enumerating objects: 25375, done.        
remote: Counting objects: 100% (10533/10533), done.        
remote: Compressing objects: 100% (1111/1111), done.        
remote: Total 25375 (delta 9501), reused 9709 (delta 9420), pack-reused 14842        
Receiving objects: 100% (25375/25375), 112.39 MiB | 14.66 MiB/s, done.
Resolving deltas: 100% (12257/12257), done.
error: invalid path 'collections/ordinal memes "the classics"/inscriptions.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning ?

**Comment by cliobitcoinbank** [comment]
no clue, maybe the folder names or heirchy is incorrect somehow.
"error: invalid path 'collections/ordinal memes "the classics"/inscriptions.json'"
maybe it's that?

**Comment by monooz23** [comment]
thanks for the reply
Yes, definitely believe it is this memes folder.....but how to remove to enable cloning?

**Comment by onezeromore** [comment]
I also tried to clone your repository "ordinals-collections" on Windows, but there are problems because the path "collections/ordinal memes "the classics"/inscriptions.json" contains quotes which are not allowed on Windows.

Could you please adjust the path or provide an alternative method to use the repository on Windows? I look forward to working with your project.

Thank you very much!
