### ISSUE TITLE
Collection merged but not showing on market

### ISSUE THREAD

**Issue by dilukangelosl** [ordinals-wallet/ordinals-collections#2927]
Hey Our collection was merged 

https://github.com/ordinals-wallet/ordinals-collections/pull/2913
Its a brc721, but still it does not show on the market. Is there other steps to be done

**Comment by dilukangelosl** [comment]
https://ordinals.market/collection/ordinals/bitcoinogapeclub/d5fe019404dc33bec78a111b8fa34969d98b734a5eba022dae48789ae9bdba83i0?tab=info

BRC721 Data not shown

**Comment by starbreeders-singularity-dao** [comment]
most of the traits are wrong, because your website is using outdated data. please fix and use the most recent json of "starbreeders" folder
