### ISSUE TITLE
Its been 2 months that the website is not matching the repo. Please do something

### ISSUE THREAD

**Issue by minidogenft** [ordinals-wallet/ordinals-collections#3178]
Hi there, 

Multiple collection owners have the same problem, the ordinals wallet website is not in line with the repo.

It's not good for creators if their collections info is not matching with what is shown on ordinals wallet. 

In our case, our collection ordinal-mini-doges is not updated for 2 months (15 ordinals from this collection are now in another collection, we have to update this info on ordinals wallet asap now).
Our second collection pixel-doges is not even showing on the website but well updated in this repo.

Can you please do something to fix it? it's been 2 months now. We have 15 ordinals from our first collection that need to be removed, it is important for us. 

What is going on ? We don't have answers from anyone managing this repo. I implore you to tell us something at least.

**Comment by starbreeders-singularity-dao** [comment]
Yes we are waiting dudes! And you wont sell what you dont have listed. what's the point here?

**Comment by shizz-x** [comment]
@MillHaus33

**Comment by utxo-detective** [comment]
yes
