### ISSUE TITLE
Please check the existence of this inscriptionsId in both collections.

### ISSUE THREAD

**Issue by Demon-devil** [ordinals-wallet/ordinals-collections#3568]
Please check the existence of this inscriptionsId in both collections.
ID:2f4b5b57dfb6ebb9a0174b1b7a53e33eab29198a6febbd7c34136508dedccaf5i0
Collection: seize-ctrl and bitcoin_masterpieces

**Comment by utxo-detective** [comment]
what should be done about it?

**Comment by Demon-devil** [comment]
May I inquire if this is a normal situation?

**Comment by utxo-detective** [comment]
its uncommon, but can happen. for ex. some are sub-10k collection and also in other collections
