### ISSUE TITLE
New Collection | CoOM Battles

### ISSUE THREAD

**Issue by Axiantor** [ordinals-wallet/ordinals-collections#3585]
Hi,

I want to submit collection, therefore I have created repository https://github.com/Axiantor/coombattles, but I am not able to create a pull request. New to github.
Could you please check and tell me what I have to do?

Thank you.

**Comment by utxo-detective** [comment]
ill just add coom battles myself since we minted it

**Comment by Axiantor** [comment]
That's amazing! :D
Discard my telegram message then. Appreciate your help!

**Comment by Axiantor** [comment]
After you add it does ord.io pulls it automatically to their site?

**Comment by Axiantor** [comment]
[inscriptions.zip](https://github.com/ordinals-wallet/ordinals-collections/files/12327078/inscriptions.zip)
[meta.zip](https://github.com/ordinals-wallet/ordinals-collections/files/12327079/meta.zip)
Just uploading files. Not sure if you were waiting for this.
Let me know if something is missing. Haven't seen the PR anywhere. :p
