### ISSUE TITLE
 updated inscriptions.json merged but changes not reflected on website.

### ISSUE THREAD

**Issue by Bird-NZ** [ordinals-wallet/ordinals-collections#3639]
This commit was to fix the names of some ordinal inscriptions, but I'm not seeing this reflected on the website despite this update inscriptions.json with the correct ordinal names being merged.

_Originally posted by @Bird-NZ in https://github.com/ordinals-wallet/ordinals-collections/issues/3630#issuecomment-1687221601_

**Comment by chrisconfirm** [comment]
@Bird-NZ You don't do anything wrong. In some cases, there are sync issues from repo to website, in other cases it may take some time. Thank you for your patience.

@utxo-detective can you sync this collection?

**Comment by Bird-NZ** [comment]
I am still seeing the issue. Can this please be left open?
