### ISSUE TITLE
Collection Not Showing Up

### ISSUE THREAD

**Issue by TheBenMeadows** [ordinals-wallet/ordinals-collections#3807]
Did I do something wrong with the formatting on this one?

https://github.com/ordinals-wallet/ordinals-collections/tree/main/collections/ben-and-twick

The collection isn't showing up at:

https://ord.io/collection/ben-and-twick

**Comment by chrisconfirm** [comment]
it takes some time for the website to sync to the latest git version. thank you for your understanding.

**Comment by chrisconfirm** [comment]
closing pr. please note: this is the repo for ordinalswallet.com, not for ord.io which was mentioned above.
