### ISSUE TITLE
Elfblocks

### ISSUE THREAD

**Issue by Davebitcoin** [ordinals-wallet/ordinals-collections#408]
Please check elfblocks collection, and say me what's the trouble ?
Thanks 

@MillHaus33 

https://ordinalswallet.com/collection/elfblocks

![Screenshot_20230303_010813_Chrome](https://user-images.githubusercontent.com/126721442/222596362-da9664a3-d6c4-4bed-8ad0-77eb2e2e2645.png)

**Comment by MillHaus33** [comment]
added
