### ISSUE TITLE
When will my collection get listed?

### ISSUE THREAD

**Issue by 123dobby** [ordinals-wallet/ordinals-collections#466]
@MillHaus33 

Hi, I want to follow up to see when we can get listed.

**Comment by MillHaus33** [comment]
what is the collection?

**Comment by oinoice** [comment]
Soon. Devs are doing great job keeping up. 

I've had over 1 week delays with ordx and ordswap (Still waiting for ordx). 

If you take a peak at all the pull requests for collections that have been merged, they generally get them out within 1-3 days depending on the current load open.

**Comment by starbackr** [comment]
would be awesome to get listed soon - all pull request checks passed 

starbreeders

**Comment by challengepunks** [comment]
@MillHaus33 our collection : "challenge punks"

**Comment by 123dobby** [comment]
@MillHaus33  Here's my collection #26   We're waiting for more than 2 weeks now. Please let me know if there's anything to do from our side. Thanks
