### ISSUE TITLE
Ordinals metadata composer

### ISSUE THREAD

**Issue by sherbakovdev** [ordinals-wallet/ordinals-collections#477]
Hey. I've made a simple metadata composer to help artists to generate needed files.

Repo: https://github.com/sherbakovdev/ordinals-metadata-composer
Live: https://ordinals-metadata-composer.vercel.app

**Comment by MillHaus33** [comment]
very cool. gonna add it to the readme. what is your twitter handle?

**Comment by sherbakovdev** [comment]
Thank you! All comments and suggestions are welcome! Twitter: poyo_ethOn 3. Mar 2023, at 21.47, MillHaus33 ***@***.***> wrote:﻿
very cool. gonna add it to the readme. what is your twitter handle?
