### ISSUE TITLE
How to pull request for a collection? 

### ISSUE THREAD

**Issue by ShadowLedger** [ordinals-wallet/ordinals-collections#505]
I have the inscription.json and the meta.json file  ready but i am not sure now how to pull a request for the collection listing now. 
Project Name: Shadow Ledger
Collection Name: Fiat Printers
10 Total Inscriptions.

**Comment by spzjulien** [comment]
did u try to search and learn ?
digging/learning is the key in life, no only selll ordinals ;)
https://www.youtube.com/watch?v=yXT1ElMEkW8

**Comment by MillHaus33** [comment]
@ShadowLedger find someone that knows how to make a PR and have them help you
