### ISSUE TITLE
I cant pull request for my collection.

### ISSUE THREAD

**Issue by AmazonWarriorsWorld** [ordinals-wallet/ordinals-collections#529]
I made my own collection, i have meta.json and  inscription.json.
Help me please.

**Comment by spzjulien** [comment]
whats the problem ?

**Comment by AmazonWarriorsWorld** [comment]
i cant pull request for add my collection on ordinals wallet

**Comment by spzjulien** [comment]
if u dont exmplain your problem u will never get any help 
good luck to you

**Comment by AmazonWarriorsWorld** [comment]
I want to get help, but i cant explain it to u.
I have created my own collection, i have all inscriptions. I wanna upload them in ordinals wallet, but i dont know how to do that. I know that i need too put my 2 json files into the pull request, but i dont know how to do this cuz i don't know anything about github. What i need to do? If i tap on "new pull request" it said to me "Choose different branches or forks above to discuss and review changes." i choose main and main and dont understand what to do next..

**Comment by MillHaus33** [comment]
@AmazonWarriorsWorld find someone that knows how to make a PR and have them help you
