### ISSUE TITLE
updated collections but only showing on https://openordex.org

### ISSUE THREAD

**Issue by spzjulien** [ordinals-wallet/ordinals-collections#569]
hi, 
i'm updated my ordirobots days ago, pull ok 
but not showing on ordinals wallet but update can be seen on :

https://openordex.org/collection?slug=ordirobots
vs 
https://ordinalswallet.com/collection/ordirobots

**Comment by winaung47** [comment]
ငါနားမလည်လို့ရောင်းထားပါတယ်

**Comment by MillHaus33** [comment]
check now

**Comment by spzjulien** [comment]
thanks !
