### ISSUE TITLE
How to add collection to ordinals wallet marketplace with pull request

### ISSUE THREAD

**Issue by ALPHAbet2023** [ordinals-wallet/ordinals-collections#651]
Hey,

I'm completely new to this technology.

I have created a meta.json and inscription.json for my Ordinal collection but I don't know how to create a pull request to add them to the site.

I would be very grateful if you could advise on how to do the pull request. This would be v much appreciated!

Thank you for all your good work 🙏🙏🙏

**Comment by ordcreAture** [comment]
first off you fork your own copy of the directory (by clicking fork)

then you add a file to this fork you have in your github account. type /collections/"collectionname"/meta.json to create a tree for your collection.

then copy and paste your meta.json file in. submit.

do the same for inscriptions.json

then once done with adding both those files, find the button that says "contribute" and click that.

this is submitting the Pull Request that gets your collection added. name it something sensical, leave a comment saying how happy you are that ordcreAture typed this guide up, and then submit your PR. That easy :)

**Comment by asdfqww** [comment]
hi, can u help me pls. I have prob with my pull request. Just automatically rejects the request and I don't know what to do, the files have no errors or something like that, but the request is still rejected, please help, I would  be really grateful🙏🙏🙏

**Comment by asdfqww** [comment]
my pull request number is 649, can u check pls..
