### ISSUE TITLE
How can we solve this circleci validate ????

### ISSUE THREAD

**Issue by pullrequesters** [ordinals-wallet/ordinals-collections#717]
All checks have failed
1 failing check
ci/circleci: validate — Your tests failed on CircleCI
Required
[Details](https://circleci.com/gh/ordinals-wallet/ordinals-collections/1433)
This pull request can be automatically merged by project collaborators
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by MillHaus33** [comment]
are you good now?

**Comment by pullrequesters** [comment]
yes, but i dont understand why first it shown up my meta.json on ordinalswallet.com but now it shows "Inscriptions #undefined-undefined" and no photo, ive waited i tought its some delay, today i made an update for meta.json, so will see, thank you
