### ISSUE TITLE
The flower Faces 
 

### ISSUE THREAD

**Issue by cyberbaloch33** [ordinals-wallet/ordinals-collections#732]
The flower faces is a new and uniqe art provided by me. I create a 42 nft's and each nft is different and uniqe.
I wants to launch my collection on Ordinals supported btc chain...
Opensea(theflowerface)![Screenshot_2023-03-07-22-31-38-66_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/120189378/223502209-76e0e046-01f5-4ca1-b082-8333bb399867.jpg)

![Screenshot_2023-03-07-22-31-21-48_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/120189378/223502210-2123a567-592c-42ab-a21d-3451ca0a61ba.jpg)

**Comment by cyberbaloch33** [comment]
@ordinal-hodlers anyone advice me!!
I wants to launch my collection on Ordinals?
Please Response

**Comment by cyberbaloch33** [comment]
@ordinal-hodlers anyone advice me!!
I wants to launch my collection on Ordinals?
Please Response

**Comment by jamesawhite465** [comment]
Do some research, this is not the place to ask
