### ISSUE TITLE
How to add collection to ordinals wallet marketplace

### ISSUE THREAD

**Issue by asdfqww** [ordinals-wallet/ordinals-collections#892]
I need help. I downloaded literally everything, both files, no errors in them, but my request was still denied. Maybe I'm doing something wrong, which is why my request is rejected 15 seconds after creation. My pull request number is 797. II would be very grateful if you could advise on how to do the pull request. This would be v much appreciated! 🙏🙏🙏

**Comment by MillHaus33** [comment]
![image](https://user-images.githubusercontent.com/28199074/224490637-2b4432f6-dbe4-4e34-8747-4d6fa4e53105.png)
reduce slug length, should be good
